package com.sam.bluepad.domain.ble

enum class BLEPropertyType {
	PROPERTY_BROADCAST,
	PROPERTY_READ,
	PROPERTY_WRITE_NO_RESPONSE,
	PROPERTY_WRITE,
	PROPERTY_NOTIFY,
	PROPERTY_INDICATE,
	PROPERTY_SIGNED_WRITE,
	PROPERTY_EXTENDED_PROPS,
	UNKNOWN,
}