config:
    validation: true
    warningsAsErrors: false
    checkExhaustiveness: false
    excludes: [ ]

processors:
    active: true

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'
        - 'ComplexityReport'
        - 'NotificationReport'
        - 'IssuesReport'
        - 'FileBasedIssuesReport'

comments:
    active: true
    AbsentOrWrongFileLicense:
        active: false
    DeprecatedBlockTag:
        active: false
    DocumentationOverPrivateFunction:
        active: false
    DocumentationOverPrivateProperty:
        active: false
    EndOfSentenceFormat:
        active: false
    KDocReferencesNonPublicProperty:
        active: false
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
    OutdatedDocumentation:
        active: false
    UndocumentedPublicClass:
        active: false
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
    UndocumentedPublicFunction:
        active: false
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
    UndocumentedPublicProperty:
        active: false
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]

complexity:
    active: true
    CognitiveComplexMethod:
        active: false
    ComplexCondition:
        active: true
        allowedConditions: 3
    ComplexInterface:
        active: false
    CyclomaticComplexMethod:
        active: true
        allowedComplexity: 15
        nestingFunctions:
            - 'also'
            - 'apply'
            - 'forEach'
            - 'let'
            - 'run'
            - 'use'
            - 'with'
    LabeledExpression:
        active: false
    LargeClass:
        active: true
        allowedLines: 600
    LongMethod:
        active: true
        allowedLines: 80
    LongParameterList:
        active: true
        allowedFunctionParameters: 6
        allowedConstructorParameters: 8
        ignoreDataClasses: true
    NestedBlockDepth:
        active: true
        allowedDepth: 4
    StringLiteralDuplication:
        active: false
    TooManyFunctions:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
        allowedFunctionsPerFile: 20
        allowedFunctionsPerClass: 20
        allowedFunctionsPerInterface: 20
        allowedFunctionsPerObject: 20

coroutines:
    active: true
    CoroutineLaunchedInTestWithoutRunTest:
        active: false
    GlobalCoroutineUsage:
        active: false
    InjectDispatcher:
        active: true
    RedundantSuspendModifier:
        active: true
    SleepInsteadOfDelay:
        active: true
    SuspendFunWithFlowReturnType:
        active: true

empty-blocks:
    active: true
    EmptyCatchBlock:
        active: true
        allowedExceptionNameRegex: '_|(ignore|expected).*'
    EmptyClassBlock:
        active: false
    EmptyDefaultConstructor:
        active: true
    EmptyFunctionBlock:
        active: true
        ignoreOverridden: true
    EmptyIfBlock:
        active: true

exceptions:
    active: true
    ExceptionRaisedInUnexpectedLocation:
        active: true
    PrintStackTrace:
        active: true
    RethrowCaughtException:
        active: true
    SwallowedException:
        active: true
        allowedExceptionNameRegex: '_|(ignore|expected).*'
    TooGenericExceptionCaught:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]

naming:
    active: true
    BooleanPropertyNaming:
        active: false
    ClassNaming:
        active: true
        classPattern: '[A-Z][a-zA-Z0-9]*'
    FunctionNaming:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
        functionPattern: '[a-z][a-zA-Z0-9]*'

    MatchingDeclarationName:
        active: true
        mustBeFirst: true
        multiplatformTargets:
            - 'common'
            - 'jvm'
            - 'android'
            - 'desktop'
            - 'macos'
            - 'macosArm64'
            - 'macosX64'
            - 'ios'
            - 'iosArm64'
            - 'iosX64'
            - 'mingwX64'
            - 'linuxX64'

    PackageNaming:
        active: true
        packagePattern: '[a-z_]+(\.[a-z_][a-zA-Z0-9_]*)*'

    InvalidPackageDeclaration:
        active: true

performance:
    active: true
    ArrayPrimitive:
        active: true
    ForEachOnRange:
        active: true
    SpreadOperator:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]

potential-bugs:
    active: true
    AvoidReferentialEquality:
        active: true
        forbiddenTypePatterns:
            - 'kotlin.String'
    DoubleMutabilityForCollection:
        active: true
    EqualsWithHashCodeExist:
        active: true
    IgnoredReturnValue:
        active: true
    UnsafeCallOnNullableType:
        active: true
        excludes: [ '**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/desktopTest/**', '**/macosTest/**', '**/iosTest/**' ]
    UnsafeCast:
        active: true

style:
    active: true

    BracesOnIfStatements:
        active: false

    ExpressionBodySyntax:
        active: false

    MandatoryBracesLoops:
        active: false

    ForbiddenComment:
        active: true
        comments:
            -   reason: 'Forbidden FIXME marker in comment.'
                value: 'FIXME:'
            -   reason: 'Forbidden STOPSHIP marker in comment.'
                value: 'STOPSHIP:'

    MaxLineLength:
        active: true
        maxLineLength: 120
        excludePackageStatements: true
        excludeImportStatements: true
        excludeRawStrings: true

    ReturnCount:
        active: true
        max: 3
        excludeGuardClauses: true

    UnusedPrivateClass:
        active: true
    UnusedPrivateFunction:
        active: true
    UnusedPrivateProperty:
        active: true
